### PR TITLE
Arthropod Association Survey

### PR DESCRIPTION
**Pull request by mgietzmann**
Resolves https://github.com/earthwiseaware/field_surveys/issues/11

### CODE REVIEW

**Comment by mgietzmann** [comment]
First draft pics.
Screenshot 2022-04-30 090235

Screenshot 2022-04-30 090504

Screenshot 2022-04-30 090403

**Comment by mgietzmann** [comment]
For each order we could have conditionals that allow us to specify the developmental stage of the arthropod. @Cloneill-2021 to provide more details.

**Comment by Cloneill-2021** [comment]
Actually, just found the prototype. There is an issue on the ESRI side (it'll be easier to explain this Monday), but I am now able to see sth...

**Comment by Cloneill-2021** [comment]
From the top down in the app screen, we should have:
[A] Main page or tab
- the identifier: the iNat profile name [or] email ?
- the date // data filled automatically 
- the time // data filled automatically
- the location (map-collapse) // data filled automatically
- Rainy day check box (maybe)

[2] Subsequent pages/groups or tabs

- Group or Tab 1 > the arthropod
-- subitem > developmental phase > embedded in each selection - As arthropod express their developmental phases differently depending on the order in which it belongs // answer optional
-- subitem > activity (at the level of the group) > a list to pick from // answer optional
-- subitem > note field (per group) with word auto-completion // answer optional
ⓘ EwA Arthropod classification details > [here](https://docs.google.com/spreadsheets/d/1VREQaaegLvxuYyxlyMf8JFb1Ffxmk90MUDSgAS7Mz44/edit#gid=0)

- Group or Tab 2 > the host plant 
-- subitem > phenology // answer optional
-- subitem > note field (per group) with word auto-completion // answer optional
ⓘ EwA plant classification details > in progress

Temperature is not necessary: theoretically, the data can be retrieved based on location + time
For the images, once we have all the orders + plant groups we want, then I can make a community call for drawings (that we could render as stencils). Worse case, I do the drawings myself if nobody answers the call.

**Comment by mgietzmann** [comment]
@Cloneill-2021 updated the survey to match what you'd put together and republished. :)

**Comment by mgietzmann** [comment]
@Cloneill-2021 in order to include this code in our records you have to _merge_ not close.

**Comment by mgietzmann** [comment]
Let's hold off on messing with this PR until we can meet and I can show you what needs to be done.

**Comment by Cloneill-2021** [comment]
Yep. I sent you a slack to tell you that I probably did something wrong.
You'll have to show me around that platform.

Cheers! - Claire
Earthwise Aware <https://www.earthwiseaware.org/> | Executive Director
✉ ***@***.***
✆ +1 781-883-5970 | LinkedIn Profi <https://www.linkedin.com/in/coneill/>le
<https://www.earthwiseaware.org/>

<https://www.earthwiseaware.org/>

Nature Conservation as a Way Of Life

ⓘ *www.earthwiseaware.org <https://www.earthwiseaware.org>* | *EwA
Newsletter Signup » <https://eepurl.com/dl0mdD>*

🧡 Become an EwA #ScienceForAll Ambassador » *Donate
<https://www.paypal.com/donate?token=Yzw6GUsevRISYKwaJbfYLFuROgR--S6hYUi3MXy17zaRF2wzQFFJOdYXXvOFAyi-QPwNaBSfSTadFvI2>*

**Review by Cloneill-2021 — APPROVED** [review]

**Pull request merged**
